#!/usr/bin/env python3

import argparse
import json

from logics.preprocess import Preprocessor


def read_args(args=None):
    parser = argparse.ArgumentParser(
        prog='Text Analyzer project',
    )
    # General arguments
    parser.add_argument('-t', '--task',
                        help="task number",
                        required=True
                        )
    parser.add_argument('-s', '--sentences',
                        help="Sentence file path",
                        )
    parser.add_argument('-n', '--names',
                        help="Names file path",
                        )
    parser.add_argument('-r', '--removewords',
                        help="Words to remove file path",
                        )
    parser.add_argument('-p', '--preprocessed',
                        action='append',
                        help="json with preprocessed data",
                        )
    # Task specific arguments
    parser.add_argument('--maxk',
                        type=int,
                        help="Max k",
                        )
    parser.add_argument('--fixed_length',
                        type=int,
                        help="fixed length to find",
                        )
    parser.add_argument('--windowsize',
                        type=int,
                        help="Window size",
                        )
    parser.add_argument('--pairs',
                        help="json file with list of pairs",
                        )
    parser.add_argument('--threshold',
                        type=int,
                        help="graph connection threshold",
                        )
    parser.add_argument('--maximal_distance',
                        type=int,
                        help="maximal distance between nodes in graph",
                        )

    parser.add_argument('--qsek_query_path',
                        help="json file with query path",
                        )
    return parser.parse_args(args)


def main():
    args = read_args()
    ...


if __name__ == "__main__":
    data = Preprocessor(question_number=1,
                        sentences_path="examples/Q1_examples/example_1/sentences_small_1.csv",
                        peoples_path="examples/Q1_examples/example_1/people_small_1.csv",
                        remove_words_path="data/REMOVEWORDS.csv"
                        )
    print(json.dumps(data.to_json()))
    assert data.to_json() == {
        "Question 1": {
            "Processed Sentences": [
                [
                    "tuft",
                    "jet",
                    "black",
                    "forehead",
                    "dumbledore",
                    "mcgonagall",
                    "curiously",
                    "shaped",
                    "cut",
                    "like",
                    "bolt",
                    "lightning"
                ],
                [
                    "whispered",
                    "professor",
                    "mcgonagall"
                ],
                [
                    "dumbledore",
                    "dumbledore",
                    "ll",
                    "scar",
                    "forever",
                    "couldn",
                    "something",
                    "scar",
                    "dumbledore",
                    "wouldn"
                ],
                [
                    "scars",
                    "handy"
                ],
                [
                    "left",
                    "knee",
                    "perfect",
                    "map",
                    "london",
                    "underground"
                ],
                [
                    "well",
                    "dumbledore",
                    "hagrid",
                    "better",
                    "dumbledore",
                    "took",
                    "harry",
                    "harry",
                    "arms",
                    "turned",
                    "toward",
                    "dursley",
                    "dursley",
                    "dudley",
                    "dursley",
                    "house"
                ],
                [
                    "good",
                    "bye",
                    "harry",
                    "sir",
                    "asked",
                    "hagrid"
                ],
                [
                    "harry",
                    "bent",
                    "harry",
                    "great",
                    "shaggy",
                    "harry",
                    "gave",
                    "scratchy",
                    "whiskery",
                    "kiss"
                ],
                [
                    "suddenly",
                    "hagrid",
                    "howl",
                    "like",
                    "wounded",
                    "dog"
                ],
                [
                    "shhh",
                    "hissed",
                    "professor",
                    "mcgonagall",
                    "ll",
                    "wake",
                    "muggles",
                    "sorry",
                    "sobbed",
                    "hagrid",
                    "taking",
                    "large",
                    "spotted",
                    "handkerchief",
                    "burying",
                    "hagrid",
                    "face",
                    "handkerchief",
                    "stand",
                    "handkerchief",
                    "lily",
                    "james",
                    "dead",
                    "poor",
                    "little",
                    "harry",
                    "ter",
                    "muggles",
                    "handkerchief",
                    "sad",
                    "grip",
                    "hagrid",
                    "ll",
                    "professor",
                    "mcgonagall",
                    "whispered",
                    "patting",
                    "hagrid",
                    "gingerly",
                    "arm",
                    "dumbledore",
                    "stepped",
                    "low",
                    "garden",
                    "wall",
                    "walked",
                    "front",
                    "door"
                ],
                [
                    "dumbledore",
                    "laid",
                    "harry",
                    "gently",
                    "doorstep",
                    "took",
                    "letter",
                    "dumbledore",
                    "cloak",
                    "tucked",
                    "letter",
                    "inside",
                    "harry",
                    "blankets",
                    "came"
                ],
                [
                    "full",
                    "minute",
                    "three",
                    "stood",
                    "looked",
                    "little",
                    "bundle",
                    "hagrid",
                    "shoulders",
                    "shook",
                    "professor",
                    "mcgonagall",
                    "blinked",
                    "furiously",
                    "twinkling",
                    "light",
                    "usually",
                    "shone",
                    "dumbledore",
                    "eyes",
                    "seemed"
                ],
                [
                    "well",
                    "dumbledore",
                    "finally"
                ],
                [
                    "ve",
                    "business",
                    "staying"
                ],
                [
                    "well",
                    "go",
                    "join",
                    "celebrations",
                    "hagrid",
                    "muffled",
                    "voice",
                    "ll",
                    "takin",
                    "sirius",
                    "sirius",
                    "bike",
                    "professor",
                    "mcgonagall",
                    "professor",
                    "dumbledore",
                    "sir",
                    "wiping",
                    "sirius",
                    "streaming",
                    "eyes",
                    "sirius",
                    "jacket",
                    "sleeve",
                    "hagrid",
                    "swung",
                    "hagrid",
                    "onto",
                    "motorcycle",
                    "kicked",
                    "engine",
                    "roar",
                    "engine",
                    "rose",
                    "air"
                ],
                [
                    "shall",
                    "expect",
                    "professor",
                    "mcgonagall",
                    "dumbledore",
                    "nodding",
                    "voice"
                ],
                [
                    "professor",
                    "mcgonagall",
                    "blew",
                    "mcgonagall",
                    "nose",
                    "reply"
                ],
                [
                    "dumbledore",
                    "turned",
                    "walked",
                    "street"
                ],
                [
                    "corner",
                    "dumbledore",
                    "stopped",
                    "took",
                    "silver",
                    "outer"
                ],
                [
                    "dumbledore",
                    "clicked",
                    "outer",
                    "twelve",
                    "balls",
                    "light",
                    "sped",
                    "balls",
                    "street",
                    "lamps",
                    "privet",
                    "drive",
                    "glowed",
                    "suddenly",
                    "orange",
                    "dumbledore",
                    "tabby",
                    "cat",
                    "slinking",
                    "corner",
                    "street"
                ],
                [
                    "dumbledore",
                    "bundle",
                    "blankets",
                    "step",
                    "number",
                    "four"
                ],
                [
                    "good",
                    "luck",
                    "harry",
                    "dumbledore",
                    "murmured"
                ],
                [
                    "dumbledore",
                    "turned",
                    "dumbledore",
                    "heel",
                    "swish",
                    "dumbledore",
                    "cloak",
                    "dumbledore"
                ],
                [
                    "breeze",
                    "ruffled",
                    "neat",
                    "hedges",
                    "privet",
                    "drive",
                    "lay",
                    "silent",
                    "tidy",
                    "inky",
                    "sky",
                    "place",
                    "expect",
                    "astonishing",
                    "things"
                ],
                [
                    "harry",
                    "potter",
                    "rolled",
                    "inside",
                    "dumbledore",
                    "blankets",
                    "without",
                    "waking"
                ],
                [
                    "small",
                    "hand",
                    "closed",
                    "letter",
                    "beside",
                    "dumbledore",
                    "dumbledore",
                    "slept",
                    "knowing",
                    "dumbledore",
                    "special",
                    "knowing",
                    "dumbledore",
                    "famous",
                    "knowing",
                    "dumbledore",
                    "woken",
                    "hours",
                    "dursley",
                    "scream",
                    "dursley",
                    "opened",
                    "front",
                    "door",
                    "milk",
                    "bottles",
                    "dumbledore",
                    "spend",
                    "next",
                    "weeks",
                    "prodded",
                    "pinched",
                    "dumbledore",
                    "cousin",
                    "dudley",
                    "dumbledore",
                    "couldn",
                    "moment",
                    "people",
                    "meeting",
                    "secret",
                    "country",
                    "holding",
                    "people",
                    "glasses",
                    "saying",
                    "hushed",
                    "voices",
                    "harry",
                    "potter",
                    "lived"
                ],
                [
                    "vanishing",
                    "glass",
                    "nearly",
                    "ten",
                    "years",
                    "passed",
                    "since",
                    "dursley",
                    "dursley",
                    "dudley",
                    "dursley",
                    "woken",
                    "dursley",
                    "dursley",
                    "dudley",
                    "dursley",
                    "nephew",
                    "front",
                    "step",
                    "privet",
                    "drive",
                    "hardly",
                    "changed"
                ],
                [
                    "sun",
                    "rose",
                    "tidy",
                    "front",
                    "gardens",
                    "lit",
                    "brass",
                    "number",
                    "four",
                    "dursley",
                    "dursley",
                    "dudley",
                    "dursley",
                    "front",
                    "door",
                    "number",
                    "crept",
                    "dursley",
                    "dursley",
                    "dudley",
                    "dursley",
                    "living",
                    "room",
                    "almost",
                    "exactly",
                    "dursley",
                    "seen",
                    "fateful",
                    "news",
                    "report",
                    "owls"
                ],
                [
                    "photographs",
                    "mantelpiece",
                    "really",
                    "showed",
                    "passed"
                ],
                [
                    "ten",
                    "years",
                    "ago",
                    "lots",
                    "pictures",
                    "looked",
                    "like",
                    "large",
                    "pink",
                    "beach",
                    "ball",
                    "wearing",
                    "different",
                    "colored",
                    "bonnets",
                    "dudley",
                    "dursley",
                    "longer",
                    "baby",
                    "photographs",
                    "showed",
                    "large",
                    "blond",
                    "riding",
                    "bicycle",
                    "carousel",
                    "fair",
                    "playing",
                    "computer",
                    "father",
                    "hugged",
                    "kissed",
                    "mother"
                ],
                [
                    "room",
                    "held",
                    "sign",
                    "another",
                    "lived",
                    "house"
                ]
            ],
            "Processed Names": [
                [
                    [
                        "attentive",
                        "wizard"
                    ],
                    []
                ],
                [
                    [
                        "bertram",
                        "aubrey"
                    ],
                    []
                ],
                [
                    [
                        "audrey",
                        "weasley"
                    ],
                    []
                ],
                [
                    [
                        "augusta",
                        "gran",
                        "longbottom"
                    ],
                    []
                ],
                [
                    [
                        "augustus",
                        "pye"
                    ],
                    []
                ],
                [
                    [
                        "augustus",
                        "rookwood"
                    ],
                    []
                ],
                [
                    [
                        "augustus",
                        "worme"
                    ],
                    []
                ],
                [
                    [
                        "auntie",
                        "muriel"
                    ],
                    []
                ],
                [
                    [
                        "aunt",
                        "marge",
                        "dursley"
                    ],
                    []
                ],
                [
                    [
                        "aurelius",
                        "dumbledore"
                    ],
                    []
                ],
                [
                    [
                        "aurora",
                        "sinistra"
                    ],
                    []
                ],
                [
                    [
                        "avery"
                    ],
                    []
                ],
                [
                    [
                        "babajide",
                        "akingbade"
                    ],
                    []
                ],
                [
                    [
                        "babayaga"
                    ],
                    []
                ],
                [
                    [
                        "babbitty",
                        "rabbitty"
                    ],
                    []
                ],
                [
                    [
                        "bagman",
                        "sr"
                    ],
                    []
                ],
                [
                    [
                        "ludo",
                        "bagman"
                    ],
                    []
                ],
                [
                    [
                        "otto",
                        "bagman"
                    ],
                    []
                ],
                [
                    [
                        "millicent",
                        "bagnold"
                    ],
                    []
                ],
                [
                    [
                        "bathilda",
                        "bagshot"
                    ],
                    [
                        [
                            "batty"
                        ]
                    ]
                ],
                [
                    [
                        "kquewanda",
                        "bailey"
                    ],
                    []
                ],
                [
                    [
                        "ballyfumble",
                        "stranger"
                    ],
                    [
                        [
                            "quin"
                        ],
                        [
                            "quivering",
                            "quintus"
                        ],
                        [
                            "quintusofthesillyname"
                        ]
                    ]
                ]
            ]
        }
    }
